'use strict';

// rc-tabs scrolls its nav on focus. Focus before the pointer action so click's
// stability checks run AFTER that scroll, not before mousedown triggers it.
async function activateTab(dialog, name, { timeout = 60000 } = {}) {
  const deadline = Date.now() + timeout;
  const remaining = () => Math.max(1, deadline - Date.now());
  const tab = dialog.getByRole('tab', { name, exact: true });
  let stage = 'visible';
  try {
    await tab.waitFor({ state: 'visible', timeout: remaining() });
    stage = 'focus';
    await tab.focus({ timeout: remaining() });
    stage = 'click';
    await tab.click({ timeout: remaining() });
    stage = 'selected';
    await dialog.getByRole('tab', { name, exact: true, selected: true })
      .waitFor({ state: 'visible', timeout: remaining() });
    const panelId = await tab.getAttribute('aria-controls', { timeout: remaining() });
    if (!panelId) throw Error('TAB_PANEL_MISSING');
    // IDs are generated by rc-tabs, not task input.
    const pane = dialog.locator(`[id=${JSON.stringify(panelId)}]`);
    stage = 'panel';
    await pane.locator('xpath=self::*[contains(concat(" ",normalize-space(@class)," ")," ant-tabs-tabpane-active ")]')
      .waitFor({ state: 'visible', timeout: remaining() });
    return pane;
  } catch (cause) {
    // Collect only structural state: no form values, task names or DOM dumps.
    const state = await dialog.locator('[role="tab"]').evaluateAll(tabs => tabs.map(tab => ({
      selected: tab.getAttribute('aria-selected'),
      disabled: tab.getAttribute('aria-disabled'),
      focused: tab === document.activeElement,
      panelVisible: (() => {
        const panel = document.getElementById(tab.getAttribute('aria-controls'));
        return !!panel && !!panel.getClientRects().length && getComputedStyle(panel).visibility !== 'hidden';
      })(),
    }))).catch(() => []);
    throw new Error(`BROWSER_TAB_ACTIVATION_FAILED:${name}:stage=${stage}:state=${JSON.stringify(state)}`, { cause });
  }
}

module.exports = { activateTab };
